name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run app.py
        run: python app.py

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run snyk test and monitor
        env:
          SNYK_TOKEN: "18f6619d-0cee-454c-b491-f026fe08e308"
        run: 
            snyk auth "18f6619d-0cee-454c-b491-f026fe08e308"
            snyk test --file=requirements.txt --command=python3 || echo "No vulnerabilities or scan failed"
            snyk monitor --file=requirements.txt \
             --command=python3 \
             --project-name=demo-public \
             --org=mounicasangana

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: "18f6619d-0cee-454c-b491-f026fe08e308"
        with:
          args: --severity-threshold=medium
