name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run app.py
        run: python app.py

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: "18f6619d-0cee-454c-b491-f026fe08e308"
        with:
          args: --severity-threshold=medium

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Monitor project with Snyk
        run: snyk monitor --org=mounicasangana --project-name=demo-public
        env:
          SNYK_TOKEN: "18f6619d-0cee-454c-b491-f026fe08e308"
